# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_open = QtWidgets.QPushButton(self.centralwidget)
        self.Button_open.setGeometry(QtCore.QRect(1260, 40, 81, 51))
        self.Button_open.setObjectName("Button_open")
        self.List_directory = QtWidgets.QListWidget(self.centralwidget)
        self.List_directory.setGeometry(QtCore.QRect(960, 520, 61, 451))
        self.List_directory.setObjectName("List_directory")
        self.qlabel_MR = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_MR.setGeometry(QtCore.QRect(10, 510, 512, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_MR.sizePolicy().hasHeightForWidth())
        self.qlabel_MR.setSizePolicy(sizePolicy)
        self.qlabel_MR.setStyleSheet("background-color:white\n"
"")
        self.qlabel_MR.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_MR.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_MR.setLineWidth(1)
        self.qlabel_MR.setMidLineWidth(0)
        self.qlabel_MR.setText("")
        self.qlabel_MR.setObjectName("qlabel_MR")
        self.qlabel_MR_crop = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_MR_crop.setGeometry(QtCore.QRect(900, 40, 300, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_MR_crop.sizePolicy().hasHeightForWidth())
        self.qlabel_MR_crop.setSizePolicy(sizePolicy)
        self.qlabel_MR_crop.setStyleSheet("background-color:white\n"
"")
        self.qlabel_MR_crop.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_MR_crop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_MR_crop.setLineWidth(1)
        self.qlabel_MR_crop.setMidLineWidth(0)
        self.qlabel_MR_crop.setText("")
        self.qlabel_MR_crop.setObjectName("qlabel_MR_crop")
        self.qlabel_overay = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_overay.setGeometry(QtCore.QRect(530, 520, 400, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_overay.sizePolicy().hasHeightForWidth())
        self.qlabel_overay.setSizePolicy(sizePolicy)
        self.qlabel_overay.setStyleSheet("background-color:white\n"
"")
        self.qlabel_overay.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_overay.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_overay.setLineWidth(1)
        self.qlabel_overay.setMidLineWidth(0)
        self.qlabel_overay.setText("")
        self.qlabel_overay.setObjectName("qlabel_overay")
        self.mr_hor = QtWidgets.QSlider(self.centralwidget)
        self.mr_hor.setGeometry(QtCore.QRect(910, 10, 251, 22))
        self.mr_hor.setMinimum(-50)
        self.mr_hor.setMaximum(100)
        self.mr_hor.setProperty("value", 0)
        self.mr_hor.setSliderPosition(0)
        self.mr_hor.setOrientation(QtCore.Qt.Horizontal)
        self.mr_hor.setObjectName("mr_hor")
        self.mr_ver = QtWidgets.QSlider(self.centralwidget)
        self.mr_ver.setGeometry(QtCore.QRect(1220, 80, 22, 251))
        self.mr_ver.setMinimum(-50)
        self.mr_ver.setMaximum(100)
        self.mr_ver.setProperty("value", 0)
        self.mr_ver.setOrientation(QtCore.Qt.Vertical)
        self.mr_ver.setObjectName("mr_ver")
        self.qlabel_CT = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_CT.setGeometry(QtCore.QRect(10, 0, 512, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_CT.sizePolicy().hasHeightForWidth())
        self.qlabel_CT.setSizePolicy(sizePolicy)
        self.qlabel_CT.setStyleSheet("background-color:white\n"
"")
        self.qlabel_CT.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_CT.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_CT.setLineWidth(1)
        self.qlabel_CT.setMidLineWidth(0)
        self.qlabel_CT.setText("")
        self.qlabel_CT.setObjectName("qlabel_CT")
        self.qlabel_CT_crop = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_CT_crop.setGeometry(QtCore.QRect(550, 40, 300, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_CT_crop.sizePolicy().hasHeightForWidth())
        self.qlabel_CT_crop.setSizePolicy(sizePolicy)
        self.qlabel_CT_crop.setStyleSheet("background-color:white\n"
"")
        self.qlabel_CT_crop.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_CT_crop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_CT_crop.setLineWidth(1)
        self.qlabel_CT_crop.setMidLineWidth(0)
        self.qlabel_CT_crop.setText("")
        self.qlabel_CT_crop.setObjectName("qlabel_CT_crop")
        self.List_MR = QtWidgets.QListWidget(self.centralwidget)
        self.List_MR.setGeometry(QtCore.QRect(1060, 770, 241, 191))
        self.List_MR.setObjectName("List_MR")
        self.Button_MR1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_MR1.setGeometry(QtCore.QRect(1190, 490, 101, 31))
        self.Button_MR1.setObjectName("Button_MR1")
        self.Button_save = QtWidgets.QPushButton(self.centralwidget)
        self.Button_save.setGeometry(QtCore.QRect(1060, 440, 101, 31))
        self.Button_save.setObjectName("Button_save")
        self.List_CT = QtWidgets.QListWidget(self.centralwidget)
        self.List_CT.setGeometry(QtCore.QRect(1060, 530, 241, 191))
        self.List_CT.setObjectName("List_CT")
        self.Button_CT1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_CT1.setGeometry(QtCore.QRect(1060, 490, 101, 31))
        self.Button_CT1.setObjectName("Button_CT1")
        self.Button_CTMR = QtWidgets.QPushButton(self.centralwidget)
        self.Button_CTMR.setGeometry(QtCore.QRect(1190, 440, 101, 31))
        self.Button_CTMR.setObjectName("Button_CTMR")
        self.CT_up = QtWidgets.QPushButton(self.centralwidget)
        self.CT_up.setGeometry(QtCore.QRect(740, 400, 25, 25))
        self.CT_up.setObjectName("CT_up")
        self.CT_left = QtWidgets.QPushButton(self.centralwidget)
        self.CT_left.setGeometry(QtCore.QRect(710, 430, 25, 25))
        self.CT_left.setObjectName("CT_left")
        self.CT_right = QtWidgets.QPushButton(self.centralwidget)
        self.CT_right.setGeometry(QtCore.QRect(770, 430, 25, 25))
        self.CT_right.setObjectName("CT_right")
        self.CT_down = QtWidgets.QPushButton(self.centralwidget)
        self.CT_down.setGeometry(QtCore.QRect(740, 460, 25, 25))
        self.CT_down.setObjectName("CT_down")
        self.MR_right = QtWidgets.QPushButton(self.centralwidget)
        self.MR_right.setGeometry(QtCore.QRect(1000, 430, 25, 25))
        self.MR_right.setObjectName("MR_right")
        self.MR_left = QtWidgets.QPushButton(self.centralwidget)
        self.MR_left.setGeometry(QtCore.QRect(940, 430, 25, 25))
        self.MR_left.setObjectName("MR_left")
        self.MR_down = QtWidgets.QPushButton(self.centralwidget)
        self.MR_down.setGeometry(QtCore.QRect(970, 460, 25, 25))
        self.MR_down.setObjectName("MR_down")
        self.MR_up = QtWidgets.QPushButton(self.centralwidget)
        self.MR_up.setGeometry(QtCore.QRect(970, 400, 25, 25))
        self.MR_up.setObjectName("MR_up")
        self.beforexy = QtWidgets.QPushButton(self.centralwidget)
        self.beforexy.setGeometry(QtCore.QRect(1150, 400, 41, 23))
        self.beforexy.setObjectName("beforexy")
        self.qlabel_MR.raise_()
        self.qlabel_CT.raise_()
        self.Button_open.raise_()
        self.qlabel_MR_crop.raise_()
        self.mr_hor.raise_()
        self.mr_ver.raise_()
        self.qlabel_CT_crop.raise_()
        self.qlabel_overay.raise_()
        self.List_directory.raise_()
        self.List_MR.raise_()
        self.Button_MR1.raise_()
        self.Button_save.raise_()
        self.List_CT.raise_()
        self.Button_CT1.raise_()
        self.Button_CTMR.raise_()
        self.CT_up.raise_()
        self.CT_left.raise_()
        self.CT_right.raise_()
        self.CT_down.raise_()
        self.MR_right.raise_()
        self.MR_left.raise_()
        self.MR_down.raise_()
        self.MR_up.raise_()
        self.beforexy.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_open.setText(_translate("MainWindow", "Open"))
        self.Button_MR1.setText(_translate("MainWindow", "MR + 1"))
        self.Button_save.setText(_translate("MainWindow", "Save"))
        self.Button_CT1.setText(_translate("MainWindow", "CT + 1"))
        self.Button_CTMR.setText(_translate("MainWindow", "CT + MR"))
        self.CT_up.setText(_translate("MainWindow", "↑"))
        self.CT_left.setText(_translate("MainWindow", "←"))
        self.CT_right.setText(_translate("MainWindow", "→"))
        self.CT_down.setText(_translate("MainWindow", "↓"))
        self.MR_right.setText(_translate("MainWindow", "→"))
        self.MR_left.setText(_translate("MainWindow", "←"))
        self.MR_down.setText(_translate("MainWindow", "↓"))
        self.MR_up.setText(_translate("MainWindow", "↑"))
        self.beforexy.setText(_translate("MainWindow", "X, Y"))

