# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_open = QtWidgets.QPushButton(self.centralwidget)
        self.Button_open.setGeometry(QtCore.QRect(1820, 730, 71, 31))
        self.Button_open.setObjectName("Button_open")
        self.List_directory = QtWidgets.QListWidget(self.centralwidget)
        self.List_directory.setGeometry(QtCore.QRect(1820, 780, 81, 231))
        self.List_directory.setObjectName("List_directory")
        self.qlabel_CT_crop = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_CT_crop.setGeometry(QtCore.QRect(530, 10, 450, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_CT_crop.sizePolicy().hasHeightForWidth())
        self.qlabel_CT_crop.setSizePolicy(sizePolicy)
        self.qlabel_CT_crop.setStyleSheet("background-color:white\n"
"")
        self.qlabel_CT_crop.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_CT_crop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_CT_crop.setLineWidth(1)
        self.qlabel_CT_crop.setMidLineWidth(0)
        self.qlabel_CT_crop.setText("")
        self.qlabel_CT_crop.setObjectName("qlabel_CT_crop")
        self.qlabel_MR = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_MR.setGeometry(QtCore.QRect(10, 520, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_MR.sizePolicy().hasHeightForWidth())
        self.qlabel_MR.setSizePolicy(sizePolicy)
        self.qlabel_MR.setStyleSheet("background-color:white\n"
"")
        self.qlabel_MR.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_MR.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_MR.setLineWidth(1)
        self.qlabel_MR.setMidLineWidth(0)
        self.qlabel_MR.setText("")
        self.qlabel_MR.setObjectName("qlabel_MR")
        self.qlabel_MR_crop = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_MR_crop.setGeometry(QtCore.QRect(1450, 30, 450, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_MR_crop.sizePolicy().hasHeightForWidth())
        self.qlabel_MR_crop.setSizePolicy(sizePolicy)
        self.qlabel_MR_crop.setStyleSheet("background-color:white\n"
"")
        self.qlabel_MR_crop.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_MR_crop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_MR_crop.setLineWidth(1)
        self.qlabel_MR_crop.setMidLineWidth(0)
        self.qlabel_MR_crop.setText("")
        self.qlabel_MR_crop.setObjectName("qlabel_MR_crop")
        self.qlabel_overay = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_overay.setGeometry(QtCore.QRect(990, 370, 450, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_overay.sizePolicy().hasHeightForWidth())
        self.qlabel_overay.setSizePolicy(sizePolicy)
        self.qlabel_overay.setStyleSheet("background-color:white\n"
"")
        self.qlabel_overay.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_overay.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_overay.setLineWidth(1)
        self.qlabel_overay.setMidLineWidth(0)
        self.qlabel_overay.setText("")
        self.qlabel_overay.setObjectName("qlabel_overay")
        self.List_CT = QtWidgets.QListWidget(self.centralwidget)
        self.List_CT.setGeometry(QtCore.QRect(1450, 690, 360, 151))
        self.List_CT.setObjectName("List_CT")
        self.List_MR = QtWidgets.QListWidget(self.centralwidget)
        self.List_MR.setGeometry(QtCore.QRect(1450, 859, 360, 151))
        self.List_MR.setObjectName("List_MR")
        self.Button_save = QtWidgets.QPushButton(self.centralwidget)
        self.Button_save.setGeometry(QtCore.QRect(1170, 290, 101, 31))
        self.Button_save.setObjectName("Button_save")
        self.Button_CT1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_CT1.setGeometry(QtCore.QRect(1030, 330, 101, 31))
        self.Button_CT1.setObjectName("Button_CT1")
        self.Button_CTMR = QtWidgets.QPushButton(self.centralwidget)
        self.Button_CTMR.setGeometry(QtCore.QRect(1170, 330, 101, 31))
        self.Button_CTMR.setObjectName("Button_CTMR")
        self.Button_MR1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_MR1.setGeometry(QtCore.QRect(1310, 330, 101, 31))
        self.Button_MR1.setObjectName("Button_MR1")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(1270, 20, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(1410, 40, 22, 160))
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.qlabel_CT = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_CT.setGeometry(QtCore.QRect(10, 10, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_CT.sizePolicy().hasHeightForWidth())
        self.qlabel_CT.setSizePolicy(sizePolicy)
        self.qlabel_CT.setStyleSheet("background-color:white\n"
"")
        self.qlabel_CT.setFrameShape(QtWidgets.QFrame.Box)
        self.qlabel_CT.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qlabel_CT.setLineWidth(1)
        self.qlabel_CT.setMidLineWidth(0)
        self.qlabel_CT.setText("")
        self.qlabel_CT.setObjectName("qlabel_CT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_open.setText(_translate("MainWindow", "Open"))
        self.Button_save.setText(_translate("MainWindow", "Save"))
        self.Button_CT1.setText(_translate("MainWindow", "CT + 1"))
        self.Button_CTMR.setText(_translate("MainWindow", "CT + MR"))
        self.Button_MR1.setText(_translate("MainWindow", "MR + 1"))

